# Generated by Django 3.1.2 on 2020-10-05 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0004_order_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='user',
            new_name='user_profile_id',
        ),
    ]
