# Generated by Django 3.1.2 on 2020-10-05 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0005_auto_20201005_1754'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='user_profile_id',
            new_name='user',
        ),
    ]
