# Generated by Django 3.1.2 on 2020-10-05 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0006_auto_20201005_1755'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='user',
            new_name='user_profile',
        ),
    ]
